export const iconList = [
    { title: 'Camera', value: 'FaCamera' },
    { title: 'Chart Line', value: 'FaChartLine' },
    { title: 'Cloud', value: 'FaCloud' },
    { title: 'Code', value: 'FaCode' },
    { title: 'Cogs', value: 'FaCogs' },
    { title: 'CSS3', value: 'FaCss3Alt' },
    { title: 'Database', value: 'FaDatabase' },
    { title: 'Figma', value: 'FaFigma' },
    { title: 'Git', value: 'FaGitAlt' },
    { title: 'Headset', value: 'FaHeadset' },
    { title: 'Lock', value: 'FaLock' },
    { title: 'Mobile', value: 'FaMobileAlt' },
    { title: 'Node.js', value: 'FaNodeJs' },
    { title: 'Paint Brush', value: 'FaPaintBrush' },
    { title: 'Project Diagram', value: 'FaProjectDiagram' },
    { title: 'React', value: 'FaReact' },
    { title: 'Search', value: 'FaSearch' },
    { title: 'Shopping Cart', value: 'FaShoppingCart' },
    { title: 'Tachometer', value: 'FaTachometerAlt' },
    { title: 'Pin', value: 'FaThumbtack' },
    { title: 'Tools', value: 'FaTools' },
    { title: 'User', value: 'FaUserAlt' },
    { title: 'Wifi', value: 'FaWifi' },
];